apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/denverdevday-gitops/infrastructure
    targetRevision: main
    path: argo-applications
  destination:
    server: https://kubernetes.default.svc
    namespace: system-setup-applications
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
